import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import NewProcurementForm from '../../new/NewProcurementForm'
const router = { push: jest.fn(), refresh: jest.fn() }
const postJson = jest.fn()
jest.mock('next/navigation', () => ({ useRouter: () => router }))
jest.mock('@/lib/api-client', () => ({ useApiClient: () => ({ postJson }) }))
const id = '73000000-0000-4000-8000-000000000001'
let questionId = 10
beforeAll(() => { Object.defineProperty(crypto, 'randomUUID', { configurable: true, value: () => `73000000-0000-4000-8000-${String(++questionId).padStart(12, '0')}` }) })
beforeEach(() => jest.clearAllMocks())
function fill() {
  fireEvent.change(screen.getByLabelText('Titre de l’appel d’offres'), { target: { value: ' Campagne ' } })
  fireEvent.change(screen.getByLabelText('Description du besoin'), { target: { value: ' Besoin marketing ' } })
  fireEvent.change(screen.getByLabelText('Date limite'), { target: { value: '2099-07-15' } })
  fireEvent.change(screen.getByLabelText('Emails des fournisseurs prévus'), { target: { value: ' Alpha@Example.com, alpha@example.com, beta@example.com ' } })
}
function success() { postJson.mockResolvedValue({ ok: true, status: 201, json: async () => ({ id }) }) }
test('sauvegarde les données nettoyées et ouvre le dashboard créé', async () => {
  success(); render(<NewProcurementForm />); fill()
  fireEvent.click(screen.getByRole('radio', { name: /^RFP$/ }))
  fireEvent.change(screen.getByLabelText('Importance : Contrôle humain'), { target: { value: '0' } })
  expect(screen.getByLabelText('Valeur d’importance : Contrôle humain')).toHaveValue(0)
  fireEvent.change(screen.getByLabelText('Valeur d’importance : Environnement'), { target: { value: '10' } })
  expect(screen.getByLabelText('Importance : Environnement')).toHaveValue('10')
  fireEvent.click(screen.getByRole('button', { name: 'Créer l’appel d’offres' }))
  await waitFor(() => expect(router.push).toHaveBeenCalledWith(`/procurements/${id}?procurementCreated=true`))
  expect(postJson).toHaveBeenCalledWith('/api/procurements', expect.objectContaining({ title: 'Campagne', description: 'Besoin marketing', phase: 'rfp', deadline_at: '2099-07-15T16:00:00.000Z', supplier_emails: ['alpha@example.com', 'beta@example.com'], criteria_importance: expect.objectContaining({ human_oversight: 0, environment: 10 }) }))
})
test('exige les champs obligatoires et focalise le résumé accessible', () => {
  render(<NewProcurementForm />)
  fireEvent.click(screen.getByRole('button', { name: 'Créer l’appel d’offres' }))
  expect(screen.getByRole('alert')).toHaveFocus()
  expect(screen.getByLabelText('Description du besoin')).toHaveAttribute('aria-invalid', 'true')
  expect(screen.getByLabelText('Date limite')).toHaveAttribute('aria-invalid', 'true')
  expect(screen.getByLabelText('Emails des fournisseurs prévus')).toHaveAttribute('aria-invalid', 'true')
  expect(postJson).not.toHaveBeenCalled()
})
test('ajoute, déduplique et retire les emails avec Entrée', () => {
  render(<NewProcurementForm />)
  const input = screen.getByLabelText('Emails des fournisseurs prévus')
  fireEvent.change(input, { target: { value: 'Alpha@example.com, ALPHA@example.com' } })
  fireEvent.keyDown(input, { key: 'Enter' })
  expect(screen.getAllByRole('button', { name: 'Retirer alpha@example.com' })).toHaveLength(1)
  expect(input).toHaveValue('')
  fireEvent.click(screen.getByRole('button', { name: 'Retirer alpha@example.com' }))
  expect(screen.queryByText('alpha@example.com')).not.toBeInTheDocument()
})
test('bloque un email invalide encore dans le champ à la soumission', () => {
  render(<NewProcurementForm />); fill()
  fireEvent.change(screen.getByLabelText('Emails des fournisseurs prévus'), { target: { value: 'invalid' } })
  fireEvent.click(screen.getByRole('button', { name: 'Créer l’appel d’offres' }))
  expect(screen.getByRole('alert')).toHaveTextContent('email')
  expect(postJson).not.toHaveBeenCalled()
})
test('configure, réordonne et supprime les questions sans téléverser de fichier', async () => {
  success(); const { container } = render(<NewProcurementForm />); fill()
  fireEvent.click(screen.getByRole('button', { name: 'Ajouter une question sur mesure' }))
  const first = screen.getByRole('group', { name: 'Question 1' })
  fireEvent.change(within(first).getByLabelText('Intitulé'), { target: { value: 'Vos outils ?' } })
  fireEvent.change(within(first).getByLabelText('Type de réponse'), { target: { value: 'single_choice' } })
  fireEvent.change(within(first).getByLabelText('Option 1 de la question 1'), { target: { value: 'A' } })
  fireEvent.change(within(first).getByLabelText('Option 2 de la question 1'), { target: { value: 'B' } })
  fireEvent.click(screen.getByRole('button', { name: 'Ajouter une question sur mesure' }))
  const second = screen.getByRole('group', { name: 'Question 2' })
  fireEvent.change(within(second).getByLabelText('Intitulé'), { target: { value: 'Joignez une preuve' } })
  fireEvent.change(within(second).getByLabelText('Type de réponse'), { target: { value: 'file' } })
  expect(container.querySelector('input[type="file"]')).toBeNull()
  fireEvent.click(screen.getByRole('button', { name: 'Monter la question 2' }))
  expect(within(screen.getByRole('group', { name: 'Question 1' })).getByLabelText('Intitulé')).toHaveValue('Joignez une preuve')
  fireEvent.click(screen.getByRole('button', { name: 'Supprimer la question 2' }))
  fireEvent.click(screen.getByRole('button', { name: 'Créer l’appel d’offres' }))
  await waitFor(() => expect(postJson).toHaveBeenCalled())
  expect(postJson.mock.calls[0][1].custom_questions).toEqual([expect.objectContaining({ label: 'Joignez une preuve', type: 'file' })])
})
test('conserve toute la configuration après une panne réseau', async () => {
  postJson.mockRejectedValue(new TypeError('Failed to fetch'))
  render(<NewProcurementForm />); fill()
  fireEvent.click(screen.getByRole('button', { name: 'Créer l’appel d’offres' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('Votre saisie est conservée')
  expect(screen.getByLabelText('Description du besoin')).toHaveValue(' Besoin marketing ')
  expect(screen.getByLabelText('Date limite')).toHaveValue('2099-07-15')
  expect(screen.getByRole('button', { name: 'Retirer alpha@example.com' })).toBeVisible()
  expect(screen.getByRole('button', { name: 'Créer l’appel d’offres' })).toBeEnabled()
})
test('relie les erreurs de choix invalides à un groupe accessible depuis le résumé', () => {
  render(<NewProcurementForm />); fill()
  fireEvent.click(screen.getByRole('button', { name: 'Ajouter une question sur mesure' }))
  fireEvent.change(screen.getByLabelText('Intitulé'), { target: { value: 'Votre hébergement ?' } })
  fireEvent.change(screen.getByLabelText('Type de réponse'), { target: { value: 'single_choice' } })
  fireEvent.change(screen.getByLabelText('Option 1 de la question 1'), { target: { value: 'France' } })
  fireEvent.change(screen.getByLabelText('Option 2 de la question 1'), { target: { value: 'france' } })
  fireEvent.click(screen.getByRole('button', { name: 'Créer l’appel d’offres' }))
  const link = within(screen.getByRole('alert')).getByRole('link', { name: 'Les options doivent être distinctes.' })
  const target = document.querySelector(link.getAttribute('href')!)
  expect(target).toHaveAttribute('tabindex', '-1')
  expect(target).toHaveAttribute('aria-invalid', 'true')
  expect(target).toHaveAttribute('aria-describedby', 'procurement-custom_questions-0-options-error')
  expect(postJson).not.toHaveBeenCalled()
})
